---
- name: the second global variable
  hosts: all
  vars:
    URL: facebook.com
  tasks:
    - name: the second global playbook
      debug:
        msg: "{{URL}}"
    vars_files: yadav.yml
  
      - name: the IP
        debug:
          msg: "{{URL}}"
...