---
- name: the second global variable
  hosts: all
  vars:
    URL: facebook.com
    URL1: flipkart.com
  tasks:
    - name: the second global playbook
      debug:
        msg: "{{URL}}"
    - name: the IP
      debug:
        msg: "{{URL1}}"
...