---
- name: install tree package playbook
  hosts: demo 
  become: yes
  tasks:
    - name: install tree pacakage
      action: yum name=httpd state=installed
      notify: restart httpd
  handlers:
    - name: restart httpd
      action: service  name=httpd state=started
...
