---
- name: Install the loop playbook
  hosts: all
  become: yes
  tasks:
    - name: loop playbook
      user: name="{{}}" state = present
      with_items:
        - murari
        - niraj
        - suraj
...