---
- name: Create users based on fruit names
  hosts: all
  become: yes
  vars:
    fruits:
      - apple
      - banana
      - orange
  tasks:
    - name: Create users
      user:
        name: "{{ item }}"
        state: present
      loop: "{{ fruits }}"

